In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import json
from matplotlib.backends.backend_pdf import PdfPages
from scipy import stats
import pandas as pd

import pennylane as qml

In [14]:
# Circuito con 4 qubit:
dev = qml.device('default.qubit', wires=4)
@qml.qnode(dev, interface=None)
def qcircuit_4_qubit_mixed():
  qml.CZ(wires=[0,3])
  qml.Snapshot(f"ket_4_qubits_entanglement_impar{1}")
  return qml.state()

In [15]:
state = qcircuit_4_qubit_mixed()
state

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [18]:
import pennylane as qml

dev = qml.device('default.qubit', wires=4)

def CZ_4(initial_state):
    @qml.qnode(dev, interface=None)
    def circuit():
        # Inicializar el estado
        if initial_state == '01':
            qml.PauliX(wires=3)
        elif initial_state == '10':
            qml.PauliX(wires=0)
        elif initial_state == '11':
            qml.PauliX(wires=0)
            qml.PauliX(wires=3)
        
        # Aplicar las puertas CZ
        
        qml.CZ(wires=[0, 3])
        
        qml.Snapshot(f"ket_4_qubits_entanglement_impar_{initial_state}")
        return qml.state()
    
    return circuit()

# Estados iniciales posibles
initial_states = ['00', '01', '10', '11']

# Ejecución del circuito para cada estado inicial
for state in initial_states:
    result = CZ_4(state)
    print(f"Estado inicial {state}:")
    print(result)
    print("\n")

Estado inicial 00:
[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 01:
[0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 10:
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 11:
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
 -1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]




In [19]:
dev = qml.device('default.qubit', wires=4)

def CZ_4(initial_state):
    @qml.qnode(dev, interface=None)
    def circuit():
        # Inicializar el estado
        if initial_state == '01':
            qml.PauliX(wires=3)
        elif initial_state == '10':
            qml.PauliX(wires=0)
        elif initial_state == '11':
            qml.PauliX(wires=0)
            qml.PauliX(wires=3)
        
        # Aplicar las puertas CZ
        
        qml.SWAP(wires=[0, 3])
        
        qml.Snapshot(f"ket_4_qubits_entanglement_impar_{initial_state}")
        return qml.state()
    
    return circuit()

# Estados iniciales posibles
initial_states = ['00', '01', '10', '11']

# Ejecución del circuito para cada estado inicial
for state in initial_states:
    result = CZ_4(state)
    print(f"Estado inicial {state}:")
    print(result)
    print("\n")

Estado inicial 00:
[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 01:
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 10:
[0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 11:
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]




In [77]:
dev = qml.device('default.qubit', wires=4)

def CNOT_4(initial_state):
    @qml.qnode(dev, interface=None)
    def circuit():
        # Inicializar el estado
        if initial_state == '01':
            qml.PauliX(wires=3)
        elif initial_state == '10':
            qml.PauliX(wires=0)
        elif initial_state == '11':
            qml.PauliX(wires=0)
            qml.PauliX(wires=3)
        
        # Aplicar las puertas CZ
        
        qml.CNOT(wires=[0, 3])
        
        qml.Snapshot(f"ket_4_qubits_entanglement_impar_{initial_state}")
        return qml.state()
    
    return circuit()

# Estados iniciales posibles
initial_states = ['00', '01', '10', '11']

# Ejecución del circuito para cada estado inicial
for state in initial_states:
    result = CNOT_4(state)
    print(f"Estado inicial {state}:")
    print(result)
    print("\n")

Estado inicial 00:
[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 01:
[0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 10:
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


Estado inicial 11:
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]




In [125]:
dev = qml.device('default.qubit', wires=4)

def CZ_4(initial_state):
    @qml.qnode(dev, interface=None)
    def circuit():
        # Inicializar el estado
        if initial_state == '01':
            qml.PauliX(wires=3)
        elif initial_state == '10':
            qml.PauliX(wires=0)
        elif initial_state == '11':
            qml.PauliX(wires=0)
            qml.PauliX(wires=3)
        
        # Aplicar las puertas CZ
        
        qml.CZ(wires=[0,3])
        
        qml.Snapshot(f"ket_4_qubits_entanglement_impar_{initial_state}")
        return qml.state()
    
    return circuit()

In [93]:
dev = qml.device('default.qubit', wires=4)

def fq_circuit(initial_state):
    @qml.qnode(dev, interface=None)
    def circuit():
        # Inicializar el estado
        if initial_state == '01':
            qml.PauliX(wires=3)
        elif initial_state == '10':
            qml.PauliX(wires=0)
        elif initial_state == '11':
            qml.PauliX(wires=0)
            qml.PauliX(wires=3)
        
        # Aplicar las puertas CZ
        qml.Hadamard(wires=[3])
        qml.SWAP(wires=[2, 3])
        qml.SWAP(wires=[0, 1])
        qml.CNOT(wires=[1, 2])
        qml.SWAP(wires=[0, 1])
        qml.SWAP(wires=[2, 3])
        qml.Hadamard(wires=[3])
        
        qml.Snapshot(f"ket_4_qubits_entanglement_impar_{initial_state}")
        return qml.state()
    
    return circuit()

In [94]:
result = CNOT_4('11')
result 

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [97]:
result = fq_circuit('11')
result

array([ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j])

In [100]:
result = CZ_4('11')
result 

array([ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j])

### General

In [17]:
# spin moment...
"""
  def CNOT_4(self, ket_0, q_obj=[0,3], tf_expect=True):
    q_objetivo, q_target = q_obj
    state_1 = self.SWAP(ket_0, [], q_obj =   [2,3], tf_expectt = tf_expect).states[-1]
    state_2 = self.SWAP(state_1, [], q_obj = [0,1], tf_expectt = tf_expect).states[-1]
    state_3 = self.CNOT(state_2, [], q_obj = [1,2], tf_expectt = tf_expect)
    state_4 = self.SWAP(state_3, [], q_obj = [0,1], tf_expectt = tf_expect).states[-1]
    state_5 = self.SWAP(state_4, [], q_obj = [2,3], tf_expectt = tf_expect).states[-1]
    return state_5
"""

'\n  def CNOT_4(self, ket_0, q_obj=[0,3], tf_expect=True):\n    q_objetivo, q_target = q_obj\n    state_1 = self.SWAP(ket_0, [], q_obj =   [2,3], tf_expectt = tf_expect).states[-1]\n    state_2 = self.SWAP(state_1, [], q_obj = [0,1], tf_expectt = tf_expect).states[-1]\n    state_3 = self.CNOT(state_2, [], q_obj = [1,2], tf_expectt = tf_expect)\n    state_4 = self.SWAP(state_3, [], q_obj = [0,1], tf_expectt = tf_expect).states[-1]\n    state_5 = self.SWAP(state_4, [], q_obj = [2,3], tf_expectt = tf_expect).states[-1]\n    return state_5\n'

In [ ]:
"""
  def __init__(self, h = 1, gir = 1.760e11, B0 = -10e-3, nf = 4, N_qubits = 1, J = 1e12, tf_noise = False,
                 noise_std = 0.01, B1_offset = 0, n_points_pulse_Ri = 2,
                 n_points_pulse_2Qbits = 2, n_swap = 1, T1 = 1e3, T2 = 1e3,
                 tf_quantum_noise = False, f_rage = 0, save_time_values = False,
                 n_points_pulse_Ri_spl = 1000, save_pulses = False, nstepsolver = 1_000,
                 version_qutip = "5", free_time = 0):
"""

In [126]:
from dll.spin_procesor_modificated import Quantum_Spin_Proces
from qutip import basis, tensor

# ket0 =  tensor([basis(2, 0)]*N_qubits)
ket_0 = tensor(basis(2, 1), basis(2, 0), basis(2, 0), basis(2, 1))



model_spin = Quantum_Spin_Proces(N_qubits = 4, n_points_pulse_Ri = 100)

state_1 = model_spin.H(ket_0, q_obj = 3, tf_expect = False).states[-1]

state_1 = model_spin.SWAP(state_1, [], q_obj = [2,3], tf_expectt = False).states[-1]
state_1 = model_spin.SWAP(state_1, [], q_obj = [0,1], tf_expectt = False).states[-1]
state_1 = model_spin.CNOT(state_1, [], q_obj = [1,2], tf_expectt = False)
state_1 = model_spin.SWAP(state_1, [], q_obj = [0,1], tf_expectt = False).states[-1]
state_1 = model_spin.SWAP(state_1, [], q_obj = [2,3], tf_expectt = False).states[-1]

state_1 = model_spin.H(state_1, q_obj = 3, tf_expect = False).states[-1]

np.round(state_1.full(),2)

array([[ 0.  +0.j  ],
       [-0.  +0.j  ],
       [ 0.  -0.j  ],
       [ 0.  -0.j  ],
       [ 0.  -0.j  ],
       [ 0.  +0.j  ],
       [ 0.  -0.j  ],
       [-0.  +0.j  ],
       [ 0.  +0.j  ],
       [-0.71+0.71j],
       [-0.  -0.j  ],
       [-0.  -0.j  ],
       [ 0.  -0.j  ],
       [-0.  -0.j  ],
       [ 0.  -0.j  ],
       [-0.  -0.j  ]])

In [141]:
from dll.gate_procesor_modificated import CompositeGateProcessor

ket_0 = tensor(basis(2, 1), basis(2, 0), basis(2, 0), basis(2, 1))

dru_circuit = CompositeGateProcessor(n_points_pulse_Ri=5, n_points_pulse_Ri_spl = 100, version_qutip="5",
                                      N_qubits = 4, tf_noise = False, tf_quantum_noise = False,
                                      ket_dru_0 = ket_0, save_intra_states=True)

s = dru_circuit.CZ_4(dru_circuit.ket_dru_0, q_obj=[0,3], tf_expect=False)
np.round(s.full(),2)

array([[-0.  -0.j  ],
       [ 0.  -0.j  ],
       [-0.  +0.j  ],
       [-0.  +0.j  ],
       [ 0.  +0.j  ],
       [-0.  -0.j  ],
       [ 0.  -0.j  ],
       [-0.  +0.j  ],
       [ 0.  +0.j  ],
       [ 0.71-0.71j],
       [ 0.  +0.j  ],
       [-0.  -0.j  ],
       [-0.  +0.j  ],
       [ 0.  +0.j  ],
       [-0.  +0.j  ],
       [ 0.  +0.j  ]])

In [142]:
result = CZ_4('11')
result 

array([ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j])

In [143]:
state_bl =  result.reshape(-1,1)
state_spin = s.full()

F = np.abs(state_bl.T @ state_spin)**2
F

array([[0.99999998]])